server:
  port: 8084

spring:
  application:
    name: store
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:h2:mem:testdb
